import { levenshtein, normalise } from '@/lib/numerology';

/**
 * Corrected spellings are generated by the engine, never by the model. The model
 * only writes prose *about* them — but `recommendation` and `whatChanges` are
 * free text, so nothing structural stops it inventing a spelling of its own.
 *
 * The prompt forbids it. Prompts drift. This does not.
 *
 * Any name-shaped token in the prose that looks like a variant of the customer's
 * name, but is not one the engine actually produced, is a fabrication and blocks
 * the report.
 */
export interface NameFinding {
  token: string;
  nearest: string;
  path: string;
}

export interface NameCheck {
  ok: boolean;
  findings: NameFinding[];
}

const words = (s: string): string[] => normalise(s).split(' ').filter(Boolean);

function walk(value: unknown, path: string, out: (s: string, p: string) => void): void {
  if (typeof value === 'string') return out(value, path);
  if (Array.isArray(value)) return value.forEach((v, i) => walk(v, `${path}[${i}]`, out));
  if (value && typeof value === 'object')
    for (const [k, v] of Object.entries(value)) walk(v, path ? `${path}.${k}` : k, out);
}

/**
 * @param sections  model output
 * @param approved  every spelling the engine produced, current included
 */
export function checkNames(sections: unknown, approved: string[]): NameCheck {
  // Every word the engine ever put its name to, plus single letters (middle
  // initials are legitimately just one character).
  const allowed = new Set<string>();
  for (const name of approved) for (const w of words(name)) allowed.add(w);

  // The customer's own name words are the yardstick for "looks like their name".
  const targets = words(approved[approved.length - 1] ?? approved[0] ?? '');
  if (!targets.length) return { ok: true, findings: [] };

  const findings: NameFinding[] = [];
  const seen = new Set<string>();

  walk(sections, '', (text, path) => {
    // Capitalised tokens only — ordinary prose words are not name candidates.
    for (const m of text.matchAll(/\b[A-Z][a-z]{2,}\b/g)) {
      const token = m[0];
      const upper = token.toUpperCase();
      if (allowed.has(upper)) continue;

      const nearest = targets
        .map((t) => ({ t, d: levenshtein(upper, t) }))
        .sort((a, b) => a.d - b.d)[0];

      // Close enough to be a spelling of their name, far enough not to be it.
      if (nearest && nearest.d > 0 && nearest.d <= 2 && upper.length >= 4) {
        const key = `${path}:${token}`;
        if (seen.has(key)) continue;
        seen.add(key);
        findings.push({ token, nearest: nearest.t, path: path || '(root)' });
      }
    }
  });

  return { ok: findings.length === 0, findings };
}

export class NameFabricated extends Error {
  constructor(public findings: NameFinding[]) {
    super(
      `Report blocked: the text contains ${findings.length} spelling(s) the engine never produced — ` +
      findings.map((f) => `"${f.token}" (near ${f.nearest})`).join(', '),
    );
    this.name = 'NameFabricated';
  }
}
